name: Linting Pipeline

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  lint-html:
    name: lint / Lint HTML files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run HTMLHint
        run: npx --yes htmlhint "**/*.html"

  lint-css:
    name: lint / Lint CSS files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run Stylelint
        run: npx --yes stylelint "**/*.css"
